### ISSUE TITLE
open roadmap tab occured an 500 error

### ISSUE THREAD

**Issue by archonwang** [sdwolf/redcaser#12]
@marius-balteanu , thanks in advanced.

I installed the plugin and used in my environment

my environment is 

```
Environment:
  Redmine version                3.3.0.stable.15842
  Ruby version                   2.2.4-p230 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
```

I used advanced_roadmap plugins
https://redmine.ociotec.com/projects/advanced-roadmap

errorlog 

```
Started GET "/projects/demo/roadmap" for 192.168.60.238 at 2016-09-28 22:04:13 +0800
Processing by VersionsController#index as HTML
  Parameters: {"project_id"=>"demo"}
  Current user: hui.wang (id=8)
  Rendered plugins/advanced_roadmap_v2/app/views/versions/_total.html.erb (14.4ms)
  Rendered versions/_overview.html.erb (5.7ms)
  Rendered plugins/advanced_roadmap_v2/app/views/versions/_info.html.erb (144.9ms)
  Rendered plugins/advanced_roadmap_v2/app/views/versions/index.html.erb within layouts/base (209.1ms)
Completed 500 Internal Server Error in 381ms (ActiveRecord: 34.9ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_request.text.erb (0.3ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_session.text.erb (1.3ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_environment.text.erb (2.6ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (0.1ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms)
  Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (13.9ms)

ActionView::Template::Error (Mysql2::Error: Unknown column 'execution_journals.version_id' in 'where clause': SELECT `execution_journals`.* FROM `execution_journals` WHERE `execution_journa
ls`.`version_id` = 1):     8: <% @versions.each do |version| %>
     9:     <h3 class="version"><%= tag 'a', :name => version.name %><%= link_to_version version %></h3>
    10:     <%= render :partial => 'versions/info', :locals => {:version => version, :issues => @issues_by_version[version], :totals => @totals} %>
    11:     <%= call_hook :view_projects_roadmap_version_bottom, :version => version %>
    12: <% end %>
    13: </div>
    14: <% end %>
  plugins/redcase/lib/redcase_override.rb:38:in `view_projects_roadmap_version_bottom'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  plugins/advanced_roadmap_v2/app/views/versions/index.html.erb:11:in `block in _plugins_advanced_roadmap_v__app_views_versions_index_html_erb___2806338928016997124_32412020'
  plugins/advanced_roadmap_v2/app/views/versions/index.html.erb:8:in `each'
  plugins/advanced_roadmap_v2/app/views/versions/index.html.erb:8:in `_plugins_advanced_roadmap_v__app_views_versions_index_html_erb___2806338928016997124_32412020'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

**Comment by cody-vibe** [comment]
Does this reproduce without redcaser installed?
If yes you should open an issue on their page https://redmine.ociotec.com/projects/advanced-roadmap/issues. 
If not then I can take a look at it over the weekend.

**Comment by archonwang** [comment]
Hi, @sdwolf , 

Thanks for your reply.

I can not reproduce the issue without redcaser.
and if I installed redcaser it occured the error.

**Comment by cody-vibe** [comment]
I am not able to reproduce this with the latest versions of advanced_roadmap and redcaser. Please make sure you have the latest versions of both plugins. 

From what I see in the stacktrace you either have an old version of redcaser or you are using the original plugin (https://bitbucket.org/bugzinga/redcase) from which this one was forked.

**Comment by marius-balteanu** [comment]
Please reopen if the issue still reproduces in the current master version.
