### ISSUE TITLE
ActiveRecord::RecordInvalid (Validation failed: Related issue cannot be blank):

### ISSUE THREAD

**Issue by marius-balteanu** [sdwolf/redcaser#8]
```
ActiveRecord::RecordInvalid (Validation failed: Related issue cannot be blank):
  plugins/redmine_redcaser/lib/redmine_redcaser/hooks/override_hook.rb:52:in `controller_issues_new_after_save'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:91:in `call_hook'
  app/controllers/issues_controller.rb:141:in `create'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by marius-balteanu** [comment]
Review 025820401eb783a61704706fd859abd9c1cea44e
